language: python

python:
- 3.6
- "3.6-dev"  # 3.6 development branch
- "3.7-dev"  # 3.7 development branch

install:
- pip install -U tox-travis
- pip install -U codecov

script:
- tox

after_success:
- codecov
